

service: 
  name: sends3configpath

provider:
  name: aws
  runtime: nodejs12.x

functions:
  sendS3Path:
    handler: handler.sendS3Path
    memorySize: 512
    timeout: 10
  events:
    - s3:
       bucket: 'hoang-le-personal-data-bucket'
       event: s3:ObjectCreated:*